# Generated by Django 2.0 on 2021-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=30)),
                ('fat', models.IntegerField()),
                ('stupid', models.IntegerField()),
                ('dumb', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
