# Generated by Django 2.0 on 2021-07-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogger',
            name='dumb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlogger',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlogger',
            name='stupid',
            field=models.IntegerField(default=0),
        ),
    ]
