# Generated by Django 2.0 on 2021-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogger', '0002_auto_20210714_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogger',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlogger',
            name='userName',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
